// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwlrneaxjkioxurqslcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3bHJuZWF4amtpb3h1cnFzbGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzU0MDEsImV4cCI6MjA2NjkxMTQwMX0.qYOKk2RTgxe93G6Qv_OJgtFaawPfyqbpxbHW7CujcHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});